# Generated by Django 4.2.20 on 2025-04-22 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('genres_json', models.TextField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_access_token', models.CharField(max_length=255)),
                ('sp_refresh_token', models.CharField(max_length=255)),
                ('token_expires', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('popularity', models.PositiveSmallIntegerField(default=0)),
                ('features', models.TextField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.artist')),
            ],
            options={
                'indexes': [models.Index(fields=['artist'], name='recommender_artist__1ad681_idx')],
            },
        ),
    ]
