# Generated by Django 5.2 on 2025-04-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('mbid', models.CharField(blank=True, max_length=36, null=True)),
                ('url', models.URLField(blank=True)),
                ('listeners', models.PositiveIntegerField(default=0)),
                ('playcount', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mbid', models.CharField(blank=True, max_length=36, null=True)),
                ('url', models.URLField(blank=True)),
                ('playcount', models.PositiveIntegerField(default=0)),
                ('match', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.artist')),
            ],
            options={
                'ordering': ['-playcount'],
                'unique_together': {('title', 'artist')},
            },
        ),
    ]
