# Generated by Django 5.2 on 2025-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_playlisttrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
    ]
