# Generated by Django 5.2 on 2025-04-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_vocalprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocalprofile',
            name='note_max',
            field=models.PositiveSmallIntegerField(default=72, help_text='…'),
        ),
        migrations.AlterField(
            model_name='vocalprofile',
            name='note_min',
            field=models.PositiveSmallIntegerField(default=60, help_text='…'),
        ),
    ]
