# Generated by Django 4.2.13 on 2025-08-31 03:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0006_userpreferences_tracksimilarity_simpletrackfeatures_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecommendationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_weight', models.FloatField(default=0.4, help_text='Content-based filtering weight', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('collaborative_weight', models.FloatField(default=0.3, help_text='Collaborative filtering weight', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('popularity_weight', models.FloatField(default=0.2, help_text='Popularity-based weight', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('trending_weight', models.FloatField(default=0.1, help_text='Trending tracks weight', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('diversity_factor', models.FloatField(default=0.3, help_text='Diversity importance (0=similar, 1=diverse)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('exploration_level', models.FloatField(default=0.2, help_text='Exploration vs exploitation trade-off', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ab_test_group', models.CharField(blank=True, help_text='A/B test group assignment', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recommendation Preference',
                'verbose_name_plural': 'User Recommendation Preferences',
                'db_table': 'music_user_preferences',
            },
        ),
    ]
