services:
  - type: web
    name: nexttrack
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate --noinput
    startCommand: gunicorn nexttrack.wsgi --log-file -
    envVars:
      - key: DJANGO_SECRET
        sync: false
      - key: LASTFM_API_KEY
        sync: false
